/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { Ayala } from "../../ayala/base/Ayala";
import { Type } from "class-transformer";
import { Grade } from "../../grade/base/Grade";
import { Oneval } from "../../oneval/base/Oneval";
import { User } from "../../user/base/User";
@ObjectType()
class Test {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  aaaaaaaaaa!: string | null;

  @ApiProperty({
    required: false,
    type: () => Ayala,
  })
  @ValidateNested()
  @Type(() => Ayala)
  @IsOptional()
  ayala?: Ayala | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => Grade,
  })
  @ValidateNested()
  @Type(() => Grade)
  @IsOptional()
  grade?: Grade | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => Oneval,
  })
  @ValidateNested()
  @Type(() => Oneval)
  @IsOptional()
  oneval?: Oneval | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;
}
export { Test };
