/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { SchoolCreateNestedManyWithoutUsersInput } from "./SchoolCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { TestCreateNestedManyWithoutUsersInput } from "./TestCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: false,
    type: () => SchoolCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SchoolCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SchoolCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  schools?: SchoolCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TestCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TestCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TestCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  tests?: TestCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}
export { UserCreateInput };
